INSERT INTO USER (DATE_OF_BIRTH,FIRST_NAME,LAST_NAME,PASSWORD,SIGN_UP_DATE,USER_NAME) VALUES (DATE '1994-02-19','UDIT','TYAGI','1234',DATE '2015-12-26','UTYAGI')
INSERT INTO USER (DATE_OF_BIRTH,FIRST_NAME,LAST_NAME,PASSWORD,SIGN_UP_DATE,USER_NAME) VALUES (DATE '1996-02-19','SHANU','TYAGI','ABCD',DATE '2001-12-13','STYAGI')
INSERT INTO USER (DATE_OF_BIRTH,FIRST_NAME,LAST_NAME,PASSWORD,SIGN_UP_DATE,USER_NAME) VALUES (DATE '2000-03-20','BHANU','TYAGI','@#$%$',DATE '2013-03-10','bTYAGI')
INSERT INTO USER (DATE_OF_BIRTH,FIRST_NAME,LAST_NAME,PASSWORD,SIGN_UP_DATE,USER_NAME) VALUES (DATE '1998-12-25','HARSH','JATAV','12#45',DATE '2015-04-26','hCHAMAR')
INSERT INTO USER (DATE_OF_BIRTH,FIRST_NAME,LAST_NAME,PASSWORD,SIGN_UP_DATE,USER_NAME) VALUES (DATE '1992-05-10','ABHISHEK','KHATANA','ABC$%^',DATE '2015-12-26','AKHATANA')


INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Udit1',FALSE , 1)
INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Udit2',FALSE , 1)
INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Shanu1',FALSE , 2)
INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Bhanu1',FALSE , 3)
INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Harsh1',FALSE , 4)
INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Harsh2',FALSE , 4)
INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Abhishek1',FALSE , 5)
INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Abhishek2',FALSE , 5)
INSERT INTO TWITTER_ACCOUNT(ACCOUNT_NAME,PROFILE_PHOTO_UPLOADED,USER_ID) VALUES ('Abhishek3',FALSE , 5)


INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (1,2)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (1,3)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (1,4)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (1,5)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (2,3)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (2,5)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (3,1)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (3,3)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (4,1)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (5,2)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (5,5)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (6,3)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (7,1)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (7,2)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (8,2)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (8,3)
INSERT INTO TWITTER_ACCOUNT_FOLLOWERS(FOLLOWED_ACCOUNTS_ID,FOLLOWERS_ID) VALUES (9,1)

INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME) VALUES ('UDIT','TYAGI')
INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME) VALUES ('SHANU','TYAGI')

INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,EMPLOYEE_ID) VALUES ('HARSH','TYAGI',1)
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,EMPLOYEE_ID) VALUES ('BHANU','TYAGI',1)
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,EMPLOYEE_ID) VALUES ('ASHOK','TYAGI',2)


